import { useEffect, useRef, useState } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { Button } from '@/components/ui/button';
import { Typewriter } from '@/components/Typewriter';
import { AnimatedCounter } from '@/components/AnimatedCounter';
import { SkillBar } from '@/components/SkillBar';
import { ProjectCard } from '@/components/ProjectCard';
import { ProjectModal } from '@/components/ProjectModal';
import { ContactModal } from '@/components/ContactModal';
import { TerminalTyper } from '@/components/TerminalTyper';
import { ParticleBackground } from '@/components/ParticleBackground';
import profileAvatar from '@/assets/profile-avatar.jpg';
import {
  Github,
  Linkedin,
  Mail,
  Phone,
  MapPin,
  Briefcase,
  Download,
  Sparkles,
  ChevronDown,
  ExternalLink,
  Code2,
  Bot,
  FileText,
  Shield,
  ArrowRight,
} from 'lucide-react';

gsap.registerPlugin(ScrollTrigger);

const projects = [
  {
    title: 'AI Content Authenticity Verifier',
    description: 'A tool to check if text is likely AI-written or human. Helps improve content trust.',
    longDescription: 'This tool analyzes text patterns to determine whether content was generated by AI or written by a human. It uses natural language processing techniques to identify telltale signs of AI-generated content, helping maintain authenticity and trust in digital communications.',
    githubUrl: 'https://github.com/AtulSharmx/AI-Content-Authenticity-Verifier',
    tags: ['NLP', 'AI Detection', 'JavaScript'],
    challenges: [
      'Building accurate detection algorithms without ML frameworks',
      'Handling various writing styles and formats',
      'Creating an intuitive user interface for results',
    ],
  },
  {
    title: 'Agecalculator.io',
    description: 'A responsive web utility to calculate age and format DOB data.',
    longDescription: 'A clean, responsive web application that calculates exact age from date of birth. Features include calculating age in years, months, days, and even seconds. Built with a focus on user experience and mobile responsiveness.',
    githubUrl: 'https://github.com/AtulSharmx/Agecalculator.io',
    tags: ['HTML', 'CSS', 'JavaScript', 'Responsive'],
    challenges: [
      'Handling edge cases for leap years',
      'Building a responsive design that works on all devices',
      'Implementing real-time calculations',
    ],
  },
  {
    title: 'AI Career Accelerator',
    description: 'An AI assistant that suggests skills and roadmaps for career growth.',
    longDescription: 'An intelligent career guidance tool that analyzes your current skills and career goals to provide personalized learning roadmaps. It suggests relevant skills, courses, and milestones to accelerate your professional growth.',
    githubUrl: 'https://github.com/AtulSharmx/AI-Career-Accelerator',
    tags: ['AI', 'Career Tech', 'JavaScript'],
    challenges: [
      'Creating intelligent skill matching algorithms',
      'Designing intuitive roadmap visualizations',
      'Building a scalable recommendation system',
    ],
  },
];

const skills = [
  { 
    name: 'HTML & CSS', 
    level: 'Practiced',
    proof: 'Built responsive and accessible web interfaces',
    color: 'from-blue-500 to-cyan-400'
  },
   { 
    name: 'C (Basics)', 
    level: 'Learning',
    proof: 'Learning core programming concepts',
    color: 'from-yellow-500 to-amber-400'
  },
  { 
    name: 'JavaScript', 
    level: 'Learning',
    proof: 'Developed interactive web applications',
    color: 'from-yellow-500 to-amber-400'
  },
  { 
    name: 'Cybersecurity Basics', 
    level: 'Learning',
    proof: 'Studying security fundamentals',
    color: 'from-yellow-500 to-amber-400'
  },
   { 
    name: 'Python Basics', 
    level: 'Learning',
    proof: 'Learning programming fundamentals',
    color: 'from-yellow-500 to-amber-400'
  },
  {
  name: 'Prompt Engineering',
  level: 'Practiced',
  proof: 'Creates effective prompts to build AI tools and automation workflows',
  color: 'from-purple-500 to-pink-400'
},
{
  name: 'AI Tools & Automation',
  level: 'Practiced',
  proof: 'Builds AI-powered tools using automation logic and problem-solving',
  color: 'from-indigo-500 to-blue-400'
},
{
  name: 'Git & GitHub',
  level: 'Practiced',
  proof: 'Manages project code, versions, and public repositories',
  color: 'from-gray-500 to-slate-400'
},
{
  name: 'UI Building (Basics)',
  level: 'Practiced',
  proof: 'Designed clean user interfaces for small web tools',
  color: 'from-teal-500 to-cyan-400'
},
{
  name: 'Problem Solving',
  level: 'Strength',
  proof: 'Builds tools from scratch by identifying problems and creating solutions',
  color: 'from-fuchsia-500 to-purple-400'
},
{
  name: 'PDF Automation',
  level: 'Practiced',
  proof: 'Created tools for PDF processing and smart data extraction',
  color: 'from-red-500 to-orange-400'
},
];

const timelineItems = [
  {
    period: '2024 – Present',
    title: 'Started BCA (Cybersecurity)',
    description: 'Learning the basics of programming and computer science. Building small tools and understanding how software works.'
  },
  {
    period: 'Early 2025',
    title: 'Learned HTML, CSS & Web Basics',
    description: 'Built simple websites and practiced UI design. Started making small web tools and improving my frontend skills.'
  },
  {
    period: 'Mid 2025',
    title: 'JavaScript & Problem Solving',
    description: 'Created interactive projects, learned DOM basics, and improved my logic by building small tools and utilities.'
  },
  {
    period: 'Late 2025',
    title: 'AI Tools & Automation',
    description: 'Started working with AI prompts, OCR, PDF automation, and building real tools that solve real problems.'
  },
  {
    period: '2026 (Goal)',
    title: 'Internship & Real Work Experience',
    description: 'Apply for internships, work with real teams, learn from mentors, and contribute to meaningful projects.'
  },
  {
    period: 'Future',
    title: 'Deep Cybersecurity & AI Skills',
    description: 'Plan to explore ethical hacking, AI security, automation systems, and build advanced tools.'
  }
];

const terminalLines = [
  { text: 'git clone https://github.com/AtulSharmx/AI-Content-Verifier', isCommand: true, delay: 40 },
  { text: 'Cloning into \'AI-Content-Verifier\'...', delay: 20 },
  { text: 'Receiving objects: 100% (47/47), done.', delay: 30 },
  { text: 'cd AI-Content-Verifier && npm install', isCommand: true, delay: 40 },
  { text: 'Installing dependencies...', delay: 20 },
  { text: '✓ Ready to build cool stuff!', delay: 30 },
];

const Portfolio = () => {
  const [contactOpen, setContactOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState<typeof projects[0] | null>(null);
  const [projectModalOpen, setProjectModalOpen] = useState(false);
  const heroRef = useRef<HTMLElement>(null);
  const projectsRef = useRef<HTMLDivElement>(null);

  const handleDownloadResume = async () => {
    try {
      const response = await fetch('/Atul_Resume.pdf');
      if (!response.ok) throw new Error('Failed to download resume');

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'Atul_Resume.pdf';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading resume:', error);
    }
  };

  useEffect(() => {
    // Hero animations
    const heroTl = gsap.timeline();
    heroTl.fromTo('.hero-content > *', 
      { opacity: 0, y: 30 },
      { opacity: 1, y: 0, duration: 0.8, stagger: 0.15, ease: 'power3.out' }
    );
    heroTl.fromTo('.hero-image',
      { opacity: 0, scale: 0.9, x: 30 },
      { opacity: 1, scale: 1, x: 0, duration: 1, ease: 'power3.out' },
      '-=0.5'
    );

    // Section animations
    gsap.utils.toArray('.animate-section').forEach((section: any) => {
      gsap.fromTo(section,
        { opacity: 0, y: 50 },
        {
          opacity: 1,
          y: 0,
          duration: 0.8,
          scrollTrigger: {
            trigger: section,
            start: 'top 85%',
            toggleActions: 'play none none reverse',
          },
        }
      );
    });

    // Parallax effect for decorative elements
    gsap.to('.parallax-slow', {
      y: -100,
      scrollTrigger: {
        trigger: 'body',
        start: 'top top',
        end: 'bottom bottom',
        scrub: 1,
      },
    });

    return () => {
      ScrollTrigger.getAll().forEach((trigger) => trigger.kill());
    };
  }, []);

  const scrollToProjects = () => {
    projectsRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-background overflow-x-hidden">
      <ParticleBackground />

      {/* Floating CTA Button */}
      <button
        onClick={() => setContactOpen(true)}
        className="fixed bottom-6 right-6 z-50 w-14 h-14 rounded-full bg-gradient-to-r from-primary to-accent text-primary-foreground shadow-lg shadow-primary/40 hover:shadow-xl hover:shadow-primary/50 hover:scale-110 transition-all duration-300 flex items-center justify-center group"
        aria-label="Hire me"
      >
        <Sparkles className="w-6 h-6 group-hover:animate-bounce" />
      </button>

      {/* Hero Section */}
      <section ref={heroRef} className="relative min-h-screen flex items-center justify-center px-4 sm:px-6 lg:px-8 pt-20 pb-12">
        {/* Decorative gradient orbs */}
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-3xl parallax-slow pointer-events-none" />
        <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-accent/20 rounded-full blur-3xl parallax-slow pointer-events-none" />

        <div className="container max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-center">
            {/* Left content */}
            <div className="hero-content space-y-6 text-center lg:text-left">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 text-primary text-sm font-medium">
                <Sparkles className="w-4 h-4" />
                Open to Internships
              </div>
              
              <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold text-foreground">
                Atul Sharma
              </h1>
              
              <h2 className="text-xl sm:text-2xl text-muted-foreground font-medium">
                Creating smart AI tools & automations · Open to internships
              </h2>
              
              <p className="text-lg text-foreground/80 max-w-lg mx-auto lg:mx-0">
                I build tools that don't exist yet — small programs that solve real problems.
              </p>

              <div className="flex items-center justify-center lg:justify-start gap-2 text-primary font-mono text-lg">
                <span className="text-muted-foreground">Building:</span>
                <Typewriter
                  words={['PDF AI', 'Automation', 'AI Text Humanizer', 'AI Career Accelerator', 'AI Smart Resume Auditor', 'Age Calculator', 'NLP', 'OCR']}
                  className="gradient-text font-semibold"
                />
              </div>
              
              <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-4 pt-4">
                <Button
                  variant="hero"
                  size="xl"
                  onClick={() => setContactOpen(true)}
                >
                  <Briefcase className="w-5 h-5" />
                  Hire me as Intern
                </Button>
                <Button
                  variant="heroOutline"
                  size="xl"
                  onClick={handleDownloadResume}
                >
                  <Download className="w-5 h-5" />
                  Download Resume
                </Button>
              </div>
            </div>
            
            {/* Right content - Profile Image */}
            <div className="hero-image flex justify-center lg:justify-end">
              <div className="relative">
                {/* Glow effect */}
                <div className="absolute inset-0 bg-gradient-to-r from-primary to-accent rounded-full blur-3xl opacity-30 scale-110" />
                
                {/* Image container */}
                <div className="relative w-64 h-64 sm:w-80 sm:h-80 lg:w-96 lg:h-96 rounded-full overflow-hidden border-4 border-primary/30 shadow-2xl float">
                  <img
                    src={profileAvatar}
                    alt="Atul - AI Tools Builder"
                    className="w-full h-full object-cover"
                  />
                </div>
                
                {/* Floating badges */}
                <div className="absolute -top-4 -right-4 glass-panel px-4 py-2 rounded-full flex items-center gap-2 animate-float-slow">
                  <Code2 className="w-4 h-4 text-primary" />
                  <span className="text-sm font-medium text-foreground">AI Tools</span>
                </div>
                <div className="absolute -bottom-4 -left-4 glass-panel px-4 py-2 rounded-full flex items-center gap-2 animate-float-slow" style={{ animationDelay: '1s' }}>
                  <Shield className="w-4 h-4 text-accent" />
                  <span className="text-sm font-medium text-foreground">Cybersecurity</span>
                </div>
              </div>
            </div>
          </div>

          {/* Scroll indicator */}
          <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 opacity-60 hover:opacity-100 transition-opacity cursor-pointer" onClick={scrollToProjects}>
            <span className="text-xs text-muted-foreground uppercase tracking-widest">Scroll</span>
            <ChevronDown className="w-5 h-5 text-primary animate-bounce" />
          </div>
        </div>
      </section>

      {/* Quick Stats */}
      <section className="relative py-16 px-4 sm:px-6 lg:px-8">
        <div className="container max-w-6xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6">
            {[
              { icon: Briefcase, label: 'Status', value: 'Open to Internships' },
              { icon: Github, label: 'GitHub Projects', value: '3+', link: 'https://github.com/AtulSharmx' },
              { icon: MapPin, label: 'Location', value: 'Gurugram, Haryana' },
              { icon: Code2, label: 'Experience', value: 'Projects & Hackathons' },
            ].map((stat, index) => (
              <div
                key={index}
                className="glass-panel-light p-4 sm:p-6 text-center group hover:border-primary/30 transition-all animate-section"
              >
                <stat.icon className="w-6 h-6 mx-auto mb-3 text-primary group-hover:scale-110 transition-transform" />
                <p className="text-xs uppercase tracking-wider text-muted-foreground mb-1">{stat.label}</p>
                {stat.link ? (
                  <a href={stat.link} target="_blank" rel="noopener noreferrer" className="text-sm sm:text-base font-semibold text-foreground hover:text-primary transition-colors flex items-center justify-center gap-1">
                    {stat.value}
                    <ExternalLink className="w-3 h-3" />
                  </a>
                ) : (
                  <p className="text-sm sm:text-base font-semibold text-foreground">{stat.value}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* About Section */}
      <section className="relative py-20 px-4 sm:px-6 lg:px-8 animate-section">
        <div className="container max-w-4xl mx-auto">
          <div className="glass-panel p-8 sm:p-12">
            <h2 className="text-3xl sm:text-4xl font-bold gradient-text mb-6">About me</h2>
            <p className="text-lg text-foreground/90 leading-relaxed mb-8">
              I enjoy building tools that don't exist yet — real, practical programs that solve everyday problems. 
              I'm a first-year BCA student with a focus on Cybersecurity, and I'm currently learning C, HTML, CSS, and JavaScript. 
              I learn fast, build fast, and love taking an idea from zero to a working project. 
              I'm also open to internship opportunities where I can grow, learn from real work, and contribute to meaningful projects.
            </p>
            <div className="flex flex-wrap gap-3">
              {['Problem solver', 'Fast learner', 'Project focused'].map((trait) => (
                <span
                  key={trait}
                  className="px-4 py-2 rounded-full bg-primary/10 text-primary border border-primary/20 text-sm font-medium"
                >
                  {trait}
                </span>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Skills Section */}
      <section className="relative py-20 px-4 sm:px-6 lg:px-8 animate-section">
        <div className="container max-w-5xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-bold text-center gradient-text mb-12">Skills</h2>
          <div className="glass-panel p-6 sm:p-8 rounded-2xl">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {skills.map((skill) => (
                <div 
                  key={skill.name}
                  className="group bg-card/50 hover:bg-card/70 border border-border/30 rounded-xl p-5 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:shadow-primary/10"
                >
                  <h3 className="text-lg font-semibold text-foreground mb-2">{skill.name}</h3>
                  <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-gradient-to-r ${skill.color} text-white mb-3`}>
                    {skill.level}
                  </span>
                  <p className="text-sm text-muted-foreground">{skill.proof}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Projects Section - Horizontal Scroll */}
      <section ref={projectsRef} className="relative py-20 px-4 sm:px-6 lg:px-8 animate-section">
        <div className="container max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold gradient-text mb-4">Projects</h2>
            <p className="text-muted-foreground">Swipe or scroll to explore my work</p>
          </div>

          {/* Horizontal scroll container */}
          <div className="relative">
            <div className="flex gap-6 overflow-x-auto pb-6 scrollbar-hide snap-x snap-mandatory px-4 -mx-4">
              {projects.map((project) => (
                <div key={project.title} className="snap-center">
                  <ProjectCard
                    title={project.title}
                    description={project.description}
                    githubUrl={project.githubUrl}
                    tags={project.tags}
                    onReadMore={() => {
                      setSelectedProject(project);
                      setProjectModalOpen(true);
                    }}
                  />
                </div>
              ))}
              
              {/* Terminal Card */}
              <div className="snap-center w-[340px] sm:w-[380px] flex-shrink-0">
                <TerminalTyper lines={terminalLines} />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact CTA Section */}
      <section className="relative py-20 px-4 sm:px-6 lg:px-8 animate-section">
        <div className="container max-w-4xl mx-auto">
          <div className="relative p-8 sm:p-12 text-center overflow-hidden rounded-2xl">
            {/* Frosted glass effect */}
            <div className="absolute inset-0 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl" />
            {/* Subtle gradient overlay */}
            <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-accent/5 rounded-2xl" />
            {/* Shine effect */}
            <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent opacity-30 rounded-2xl" />
            
            <div className="relative z-10">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-br from-primary/20 to-accent/20 border border-white/10 mb-6">
                <Sparkles className="w-8 h-8 text-primary" />
              </div>
              <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">Ready to Build Something Awesome?</h2>
              <p className="text-lg text-white/80 mb-8 max-w-lg mx-auto">
                If you're looking for someone who learns fast and builds faster, I'd love to connect.
              </p>
              <Button 
                variant="hero" 
                size="xl" 
                onClick={() => setContactOpen(true)}
                className="group relative overflow-hidden"
              >
                <span className="absolute inset-0 bg-gradient-to-r from-primary to-accent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <span className="relative z-10 flex items-center gap-2">
                  <Mail className="w-5 h-5" />
                  Reach Out
                </span>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="relative py-12 px-4 sm:px-6 lg:px-8 border-t border-border/50">
        <div className="container max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="flex items-center gap-2">
              <span className="text-2xl font-bold gradient-text">Atul</span>
              <span className="text-muted-foreground">• AI Tools Builder</span>
            </div>
            
            <div className="flex items-center gap-4">
              <a
                href="https://github.com/AtulSharmx"
                target="_blank"
                rel="noopener noreferrer"
                className="w-10 h-10 rounded-full bg-muted flex items-center justify-center text-muted-foreground hover:bg-primary hover:text-primary-foreground transition-all"
                aria-label="GitHub"
              >
                <Github className="w-5 h-5" />
              </a>
              <a
                href="https://www.linkedin.com/in/atul-sharma-869715392/"
                target="_blank"
                rel="noopener noreferrer"
                className="w-10 h-10 rounded-full bg-muted flex items-center justify-center text-muted-foreground hover:bg-primary hover:text-primary-foreground transition-all"
                aria-label="LinkedIn"
              >
                <Linkedin className="w-5 h-5" />
              </a>
              <a
                href="mailto:atulsharm0744@gmail.com"
                className="w-10 h-10 rounded-full bg-muted flex items-center justify-center text-muted-foreground hover:bg-primary hover:text-primary-foreground transition-all"
                aria-label="Email"
              >
                <Mail className="w-5 h-5" />
              </a>
              <a
                href="tel:+917206365276"
                className="w-10 h-10 rounded-full bg-muted flex items-center justify-center text-muted-foreground hover:bg-primary hover:text-primary-foreground transition-all"
                aria-label="Phone"
              >
                <Phone className="w-5 h-5" />
              </a>
            </div>
          </div>
          
          <div className="mt-8 pt-6 border-t border-border/30 text-center">
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} Atul. Built with passion and code.
            </p>
          </div>
        </div>
      </footer>

      {/* Modals */}
      <ContactModal open={contactOpen} onOpenChange={setContactOpen} />
      <ProjectModal
        project={selectedProject}
        open={projectModalOpen}
        onOpenChange={setProjectModalOpen}
      />
    </div>
  );
};

export default Portfolio;
